export const botName = 'Coins By Nature'
export const positiveMoon = ':amaze:'
export const positiveInsane = ':amaze:'
export const positiveHigh = ':awyeah:'
export const positiveMed = ':what-face:'
export const positiveLow = ':bam:'
export const positiveTiny = ':uptrend:'
export const negativeInsane = ':shitstorm:'
export const negativeMoon = ':this_is_fine_gif:'
export const negativeHigh = ':this_is_fine_gif:'
export const negativeMed = ':headwall:'
export const negativeLow = ':seriously:'
export const negativeTiny = ':downtrend:'

